### ISSUE TITLE
Can't access event data from within additionalTypes()

### ISSUE THREAD

**Issue by lightest** [mrmartineau/trak.js#9]
If additionalTypes method defined in that way:

    trak.options.additionalTypes = function() {
      UDM.evq.push(['trackEvent', trak.clean(category), trak.clean(action)]); // trak.clean(label)
      console.log('Fire additional event');
    }

and then called like `settings.additionalTypes()` it can't get access to variables `category`, `action`, `label`, etc. because it has different closure. May be you can pass those variables from `event` function as parameters of `additionalTypes` or in one object parameter?

P.S.
not sure if that's a super issue but didn't find a way to contact you directly.

**Comment by mrmartineau** [comment]
Hi @lightest, I think you might have found a fairly large bug. It definitely used to work but when I changed the implementation to use the module pattern I think I must have broken it. It doesn't look too hard to fix, however, so I will try to update it over the next few days. Thanks for finding it.

**Comment by mrmartineau** [comment]
@lightest, I have fixed this now. In essence, all you now have to do is add a parameter to the `additionalTypes` function, see below:

```js
trak.options.additionalTypes = function(opts) {
	// UDM.evq.push(['trackEvent', trak.clean(opts.category), trak.clean(opts.action)]); // trak.clean(opts.label)
	console.log('Fire additional event', opts);
}
```

Please update and let me know how you get on.

**Comment by lightest** [comment]
@mrmartineau Thanks! Actually read your update quite a long time ago but totaly forgot to provide any feedback. Everything works as required.

**Comment by mrmartineau** [comment]
@lightest glad to hear it. Thanks for raising the ticket, if you find any other issues, please let me know
